name: UiPathRunTests
on:
  push:
    branches:
      - main
jobs:
 Build:
    runs-on: windows-latest
    steps:            
      # Checkout code from this repo
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Print Working Directory
        run: pwd;
             ls
      # Use uipcli to package and deploy
      - name: Pack
        run: |
                 # Build and Deploy the Package
                 echo Packing project
                 UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package pack "D:\a\CICDActions\CICDActions\project.json" -o "Output"
       # Use uipcli to deploy
      - name: Deploy Project
        run: |
                 # Build and Deploy the Package
                 echo Deploying Package
                 #UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package deploy "Output" "https://cloud.uipath.com" DefaultTenant -A "uipatfkxtisk" -I "a6665c91-f401-4ab2-97ba-383f375238cd" -S "FsaT#oUh6$y)2lJ3" --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs OR.Monitoring" -o "OATestDev"
                 #UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package deploy "Output" "https://orchestrator.local" Default -I "a0559b2f-05f9-4644-8ba3-a496dba759b7" -S "t)qZEuNwJFyG2cZi" --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs OR.Monitoring" -o "dummyFolder"
                 UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package deploy "Output" "https://fzuiporcapnpd01.corp.footlocker.net/" Default -I "0628d50a-782e-4959-b04e-59bc55abbe47" -S "SECRET" --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs OR.Monitoring" -o "UAT1" --identityUrl "https://fzuiporcapnpd01.corp.footlocker.net/identity"
