name: UiPathRunTests
on:
  push:
    branches:
      - main
jobs:
 Build:
    runs-on: windows-latest
    steps:            
      # Checkout code from this repo
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Print Working Directory
        run: pwd;
             ls
      # Use uipcli to package and deploy
      - name: Pack and Test
        run: |
                 # Build and Deploy the Package
                 echo Packing project
                 UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package pack "D:\a\CICDActions\CICDActions\project.json" -o "Output"
      # Use uipcli to run tests
      - name: Pack and Test
        run: |
                 echo Running Tests
                 UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe test run "https://cloud.uipath.com" DefaultTenant -A uipatfkxtisk -I 505bea79-6241-4bfd-82e3-32c10cd566f2 -S a1#_0si_Tct(1$oU --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Monitoring OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs" -s "check" -o "OATestDev"
       # Use uipcli to deploy
      - name: Deploy Project
        run: |
                 # Build and Deploy the Package
                 echo Deploying Package
                 UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package deploy Output "https://cloud.uipath.com" DefaultTenant -A uipatfkxtisk -I 505bea79-6241-4bfd-82e3-32c10cd566f2 -S a1#_0si_Tct(1$oU --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Monitoring OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs" -s "check" -o "OATestDev"
       # Use uipcli to deploy
