name: UiPathRunTests
on:
  push:
    branches:
      - main
jobs:
 Build:
    runs-on: windows-latest
    steps:            
      # Checkout code from this repo
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Print Working Directory
        run: pwd;
             ls
      # Use uipcli to package and deploy
      - name: Pack
        run: |
                 # Build and Deploy the Package
                 echo Packing project
                 UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package pack "D:\a\CICDActions\CICDActions\project.json" -o "Output"
       # Use uipcli to deploy
      - name: Deploy Project
        run: |
                 # Build and Deploy the Package
                 echo Deploying Package
                 #UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package deploy "Output" "https://cloud.uipath.com" DefaultTenant -A "uipatfkxtisk" -I "a6665c91-f401-4ab2-97ba-383f375238cd" -S "FsaT#oUh6$y)2lJ3" --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs OR.Monitoring" -o "OATestDev"
                 UiPath.CLI.Windows.23.6.8581.19168\tools\uipcli.exe package deploy "Output" "https://orchestrator.local" DefaultTenant -A "uipattxuvadh" -I "6e8e3a8e-8542-41fc-bce9-99bd85d85e19" -S "*Y*1VQSLba_~Et#E" --applicationScope "OR.Folders OR.BackgroundTasks OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Settings.Read OR.Robots.Read OR.Machines.Read OR.Execution OR.Assets OR.Users.Read OR.Jobs OR.Monitoring" -o "Shared"
